stages:
  - deploy

publish:
  stage: deploy
  script:
    - npm i
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - ./publish.sh
    - rm .npmrc
  tags:
    - pp-builder
  only:
    - tags
